openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/inter-challenge
  description: Generated server url
paths:
  /api/digito_unico:
    get:
      tags:
      - api-request-controller
      operationId: digitoUnico
      parameters:
      - name: numero
        in: query
        required: true
        schema:
          type: string
      - name: multiplicador
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: idUsuario
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: integer
                format: int32
  /api/usuarios/{id}/criptografar:
    get:
      tags:
      - api-request-controller
      operationId: criptografar
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: chavePublica
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Usuario'
  /api/usuarios:
    get:
      tags:
      - api-request-controller
      operationId: getUsuarios
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      tags:
      - api-request-controller
      operationId: saveUsuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Usuario'
    delete:
      tags:
      - api-request-controller
      operationId: deleteUsuario
      parameters:
      - name: idUsuario
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
  /api/usuarios/{id}:
    get:
      tags:
      - api-request-controller
      operationId: getUsuario
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Usuario'
  /api/usuarios/{id}/calculos:
    get:
      tags:
      - api-request-controller
      operationId: getCalculosUsuario
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Calculo'
components:
  schemas:
    Calculo:
      required:
      - numero
      type: object
      properties:
        id:
          type: integer
          format: int64
        numero:
          maxLength: 2147483647
          minLength: 0
          type: string
        multiplicador:
          maximum: 1000000
          minimum: 0
          type: integer
          format: int32
        digito:
          type: integer
          format: int32
    Usuario:
      required:
      - email
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          maxLength: 400
          minLength: 0
          type: string
        email:
          maxLength: 850
          minLength: 0
          type: string
        calculos:
          type: array
          items:
            $ref: '#/components/schemas/Calculo'
